### ISSUE TITLE
Speedup CI and Git by enforcing index-version 4 via update-index

### ISSUE THREAD

**Issue by sambacha** [ethereum-optimism/optimism#10486]
**Is your feature request related to a problem? Please describe.**
Monorepo speedups are nice, this is an easy change that will be easily adoptable.

**Describe the solution you'd like**

1. Enforce monorepo git configuration

2. Support caching of vendored dependencies (i.e. submodules, etc).

## Caching Sub Modules via GitHub Actions Cache 

I have created a separate GitHub repo that contains a python script that generates a GitHub workflow that correctly caches submodules for usage. 

> [!IMPORTANT]    
> In principle, we desire that the submodules are cloned and stored in the CI cache. Then we leverage the `--reference` flag to grab objects from this local cache when initialising the submodule - incrementally updating the CI cache should always be cheaper than having to freshly clone each time. 

```bash
git submodule update --init --reference <cache>/<dep> <dep>
```

> https://github.com/sambacha/workflows-cache-submodules/tree/master

1. Parse Git Submodules: Recursively parse submodules listed in `.gitmodules`.
2. Generate Bash Scripts: Create scripts to set up a reference repository and checkout with reference.
3. GitHub Actions Workflow: Generate a workflow file that caches submodules and uses the latest `@actions/checkout` and `@actions/cache`.
4. Deduplication: Hoist nested submodules by symlinking identical submodules to reduce redundancy.

### Example generated workflow jobs:

```yaml
      - name: Setup cache
        id: cache-submodule
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/git/repo
            ~/.cache/git/submodule1
            ~/.cache/git/submodule2
          key: ${{ runner.os }}-git-${{ hashFiles('**/.git') }}
          restore-keys: |
            ${{ runner.os }}-git-

      - name: Create reference repository
        if: steps.cache-submodule.outputs.cache-hit != 'true'
        run: bash create_reference_repo.sh

      - name: Checkout with reference
        run: bash checkout_with_reference.sh
```

## Suggested settings

These settings along with defining a `~/.gitconfig.monorepo` configuration file to support commitgraph and native fsmonitor

### Pseduo Merge Bitmaps

> [see details via github.blog/open-source/git/highlights-from-git-2-46/](https://github.blog/open-source/git/highlights-from-git-2-46/)

```bash
# configure pseduo-merge bitmaps
git config bitmapPseudoMerge.all.pattern 'refs/(heads|tags)/'
git config bitmapPseudoMerge.all.threshold now
git config bitmapPseudoMerge.all.stableThreshold never

# generate a new *.bitmap file
git repack -adb
```

> [!NOTE]   
> `git refs migrate --ref-format=reftable` should be available in 2.46.0, but is not

~~~bash
git config --global pack.allowPackReuse multi
git multi-pack-index write --bitmap
git update-index --verbose --index-version 4
~~~

`~/.gitconfig.monorepo`
```cfg
[core]
    commitgraph = true
    fsmonitor = true
    writeCommitGraph = true
[feature]
    manyFiles = true
```

which can be imported through your `.gitconfig` by
~~~cfg
[include]
    path = ~/.gitconfig.monorepo
~~~

### Update Index version 4

~~~console
$ git update-index --verbose --show-index-version
2
~~~

~~~console
$ git update-index --verbose --index-version 4
index-version: was 2, set to 4
~~~

### fsmonitor daemon

> see https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/

```bash
git config core.fsmonitor true
```

```bash
git fsmonitor--daemon start
```

**`core.commitgraph`**

Git will use a commit history cache to significantly speed up history operations, such as `git log` with the `--graph` option.

**`fetch.writeCommitGraph`**

Improves performance of commands like `git push -f` and `git log --graph` by writing a commit-graph on every `git fetch`.

### Faster pack generation with multi-pack reuse

https://github.blog/2024-02-23-highlights-from-git-2-44/

### Measuring Git Performance with OpenTel

https://github.blog/2023-10-16-measuring-git-performance-with-opentelemetry/
