### ISSUE TITLE
Spec and implementation disagree about URL

### ISSUE THREAD

**Issue by karlb** [ethereum-optimism/optimism#11499]
The [OP alt-DA spec](https://specs.optimism.io/experimental/alt-da.html#da-server) requires
```
Request:
  POST /put
  Content-Type: application/octet-stream
  Body: <preimage_bytes>

Response:
  200 OK
  Content-Type: application/octet-stream
  Body: <hex_encoded_commitment>
```

But the [implementation](https://github.com/ethereum-optimism/optimism/blob/5a5dd8f44161e8e05093d92b32e102eb38fe78b6/op-alt-da/daserver.go#L56) only listens at the URL `/put/` (with trailing slash). Should the implementation change or the spec?
