### ISSUE TITLE
op-deployer v0.4.0-rc.2 gives error when run with `standard-overrides`

### ISSUE THREAD

**Issue by Melvillian** [ethereum-optimism/optimism#16618]
**Bug Description**

With v0.4.0-rc.2 (I tried v0.4.0-rc-5 but that fails at an earlier step, so I tried rc.2) when I run the following command:

```bash
bin/op-deployer apply --workdir $SOME_TEMP_WORK_DIR \
    --l1-rpc-url "${L1_ETH_RPC_URL}" \
    --private-key "${DEPLOYER_PRIVATE_KEY}"
```

using this intent.toml:

```toml
configType = 'standard-overrides'
fundDevAccounts = false
l1ChainID = 11155111
l1ContractsLocator = 'tag://op-contracts/v3.0.0-rc.2'
l2ContractsLocator = 'tag://op-contracts/v3.0.0-rc.2'
opcmAddress = '0xfbceed4de885645fbded164910e10f52febfab35'
useInterop = false

[[chains]]
  baseFeeVaultRecipient = '0x9654A3786f960dB19a64dFF16FDc34eD6090A760'
  eip1559Denominator = 50
  eip1559DenominatorCanyon = 250
  eip1559Elasticity = 6
  id = '0x00000000000000000000000000000000000000000000000000000000050e1230'
  l1FeeVaultRecipient = '0x9654A3786f960dB19a64dFF16FDc34eD6090A760'
  operatorFeeConstant = 0
  operatorFeeScalar = 0
  sequencerFeeVaultRecipient = '0x9654A3786f960dB19a64dFF16FDc34eD6090A760'

  [chains.roles]
    batcher = '0xeb807C42f290037a11ab63d2cCfF03682308B1Ba'
    challenger = '0x19FFcD2638Cb70514332254312DF196c3f80fdCB'
    l1ProxyAdminOwner = '0x9654A3786f960dB19a64dFF16FDc34eD6090A760'
    l2ProxyAdminOwner = '0xa765a3786f960db19a64dff16fdc34ed6090b871'
    proposer = '0x417aFd469A6187A9360a29272c6555BdA5B80088'
    systemConfigOwner = '0x9654A3786f960dB19a64dFF16FDc34eD6090A760'
    unsafeBlockSigner = '0xA869D0C804dd3EC83B76eC4521BE2147a25a3387'

[globalDeployOverrides]
  l2BlockTime = 1

[superchainRoles]
  ProtocolVersionsOwner = '0xfd1d2e729ae8eee2e146c033bf4400fe75284301'
  SuperchainGuardian = '0x7a50f00e8d05b95f98fe38d8bee366a7324dcf7e'
  SuperchainProxyAdminOwner = '0x1eb2ffc903729a0f03966b917003800b145f56e2'

```

I expect my OP contracts to be deployed successfully, and instead I get the error:

`Application failed: error in pipeline stage apply: cannot set superchain roles for predeployed OPCM`

**Steps to Reproduce**

```
git clone --branch op-deployer/v0.4.0-rc.2 --depth=1 https://github.com/ethereum-optimism/optimism.git && \
    cd optimism/op-deployer && \
    just build
cp intent.toml $SOME_WORK_DIR

bin/op-deployer apply --workdir $SOME_WORK_DIR \
    --l1-rpc-url "${L1_ETH_RPC_URL}" \
    --private-key "${DEPLOYER_PRIVATE_KEY}"
```

**Expected behavior**

I get a state.json file to be created, which contains the results of a successfully run of the op-deployer pipeline

**Environment Information:**

Mac Sequoia 15.5
op-deployer v0.4.0-rc.2

**Configurations:**

**Logs:**

`Application failed: error in pipeline stage apply: cannot set superchain roles for predeployed OPCM`

**Additional context**

Note that are using `standard-overrides` because we want to set the blocktime to be 1 second, which is different from the default. From skimming through the code it looks like this puts it on a different code execution path where op-deployer then gets confused by the expected initial state of the system, namely that it's trying to use a pre-deployed OPCM but it's also trying to set the superchain roles, which results in the error I pasted above. I want to use the pre-deployed OPCM because that's how contract upgrades in OP work now, and I don't care about setting the superchain roles.

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.
