### ISSUE TITLE
docker container persistent issue

### ISSUE THREAD

**Issue by huahuayu** [ethereum-optimism/optimism#2507]
Hi, my system disk is just 20GB, but have another 1T disk, so I want to use that disk for storage. But the docker compose file use `/var` dir as default.

I suggest that add an environment variable in .env file for setting a base dir for storage.

If I am right, only `optimism/infra/op-replica/docker-compose/replica.yml` needs to change.

**Comment by huahuayu** [comment]
These two local volumes consume all the disk space in the system disk. It should be configable.
```bash
$ sudo docker volume inspect op-replica_dtl
[
    {
        "CreatedAt": "2022-05-01T00:00:03Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "op-replica",
            "com.docker.compose.version": "2.4.1",
            "com.docker.compose.volume": "dtl"
        },
        "Mountpoint": "/var/lib/docker/volumes/op-replica_dtl/_data",
        "Name": "op-replica_dtl",
        "Options": null,
        "Scope": "local"
    }
]

$ sudo docker volume inspect op-replica_geth
[
    {
        "CreatedAt": "2022-04-29T11:21:05Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "op-replica",
            "com.docker.compose.version": "2.4.1",
            "com.docker.compose.volume": "geth"
        },
        "Mountpoint": "/var/lib/docker/volumes/op-replica_geth/_data",
        "Name": "op-replica_geth",
        "Options": null,
        "Scope": "local"
    }
]
```

**Comment by huahuayu** [comment]
Hi @optimisticben how do you think?

**Comment by optimisticben** [comment]
I would rather use an overlay solution instead of adding more configuration to the setup.

Something like a new yaml file, and include this in the `COMPOSE_FILE` env list.
```
---
version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  data-transport-layer:
    volumes:
      - <PATH ON LOCALHOST>:/db
  l2geth-replica:
    volumes:
      - <PATH ON LOCALHOST>:/geth
```

Using host path mapping involves localhost issues I'd rather avoid in an example deployment 😁
