### ISSUE TITLE
DTL not syncing - Issue: "Cannot read properties of null"

### ISSUE THREAD

**Issue by sanbotto** [ethereum-optimism/optimism#4235]
**Describe the bug**
DTL not syncing, causing the node to be unusable. Issue:

```
{"level":30,"time":1670293646497,"highestSyncedL1Block":13596687,"targetL1Block":13598687,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1670293647013,"eventName":"TransactionEnqueued","numEvents":24,"durationMs":11,"msg":"Processed events"}
{"level":50,"time":1670293647489,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/chaindata/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts:67:32)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async L1IngestionService._syncEvents (/chaindata/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:428:29)\n    at async L1IngestionService._start (/chaindata/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:244:9)\n    at async L1IngestionService.start (/chaindata/optimism/packages/common-ts/src/base-service/base-service.ts:69:5)\n    at async Promise.all (index 1)\n    at async L1DataTransportService._start (/chaindata/optimism/packages/data-transport-layer/src/services/main/service.ts:139:7)\n    at async L1DataTransportService.start (/chaindata/optimism/packages/common-ts/src/base-service/base-service.ts:69:5)\n    at async /chaindata/optimism/packages/data-transport-layer/src/services/run.ts:69:5"},"msg":"Caught an unhandled error"}
```

&#x200B;

**To Reproduce**
1. Create a new node, either by following the Docker way or the non-Docker way, as per described [here](https://community.optimism.io/docs/developers/build/run-a-node/).
2. If deploying using Docker, start all services with `docker compose up -d`. If deploying without Docker, start DTL running the following from the within `optimism` directory:
    ```
    cd packages/data-transport-layer
    yarn start
    ```
3. If using Docker, an extra step is needed to see the error; you'll have to run this:
    ```
    docker logs --follow optimism-dtl-1
    ```

&#x200B;

**Expected behavior**
DTL should actually sync and show no errors.

&#x200B;

**System Specs:**
 - OS: Ubuntu 20.04.5 LTS
 - Kernel: Linux 5.15.0-1026-aws
 - Package Version (or commit hash): 6528ae75b (I've also tried with the latest code pulled from GH, which right now corresponds to b1b35c9)
 - RAM: 16GB
 - vCPUs: 4
 - Disk: 1500GiB
 - Docker version (for the test that used Docker): 20.10.21

&#x200B;

**Additional context**
I have one other node running perfectly fine with this exact same config (and it's actually exactly the same because I used the same Terraform code for the deployment, and I even tried using the same exact commit the other node picked up), the only difference is that the working node was started on Nov 10 and not today (or any previous day but later than Nov 10), which should be irrelevant.

&#x200B;

**Env files for the Docker option**

`.env`:

```
NETWORK_NAME=mainnet
NODE_TYPE=full
SYNC_SOURCE=l1
HEALTHCHECK__REFERENCE_RPC_PROVIDER=REDACTED_L2_RPC
FAULT_DETECTOR__L1_RPC_PROVIDER=REDACTED_L1_RPC
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=REDACTED_L1_RPC
PORT__L2GETH_HTTP=8545
PORT__L2GETH_WS=8546
PORT__DTL=7878
PORT__HEALTHCHECK_METRICS=7300
RESTART=unless-stopped
```

`docker-compose.yml`:

```
---
version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  dtl:
    image: ethereumoptimism/data-transport-layer:0.5.48
    restart: unless-stopped
    env_file:
      - ./envs/mainnet/dtl.env
      - .env
    volumes:
      - /chaindata/optimism/dtl:/db
    ports:
      - 7878:7878
    <<: *logging

  l2geth:
    image: ethereumoptimism/l2geth:0.5.29
    restart: unless-stopped
    stop_grace_period: 3m
    entrypoint:
      - /bin/sh
      - -c
      - "/scripts/check-for-chaindata-berlin.sh && /scripts/l2geth-start.sh"
    env_file:
      - ./envs/mainnet/l2geth.env
      - .env
    volumes:
      - /chaindata/optimism/l2geth:/geth
      - ./scripts/:/scripts/
    ports:
      - 8545:8545
      - 8546:8546
    <<: *logging

  healthcheck:
    image: ethereumoptimism/replica-healthcheck:1.1.12
    restart: unless-stopped
    env_file:
      - ./envs/mainnet/healthcheck.env
      - .env
    ports:
      - 7300:7300
    <<: *logging

  influxdb:
    image: quay.io/influxdb/influxdb:2.2.0
    restart: unless-stopped
    env_file:
      - ./envs/mainnet/influxdb.env
    ports:
      - 8086:8086
    volumes:
      - /chaindata/optimism/influxdb_data:/var/lib/influxdb
```

_PS: I've also tried using images `data-transport-layer:0.5.47`, `l2geth:0.5.29`, `replica-healthcheck:1.1.12` and `influxdb:1.6`._

&#x200B;

For mainnet's `l2geth.env`, I replaced the default `SEQUENCER_CLIENT_HTTP` for the same L2 RPC endpoint used at `.env`.

&#x200B;

**Env files for the non-Docker option**

DTL's `.env`:

```
DATA_TRANSPORT_LAYER__NODE_ENV=production
DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME=mainnet
DATA_TRANSPORT_LAYER__DB_PATH=/chaindata/optimism/packages/data-transport-layer/db
DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0xdE1FCfB0851916CA5101820A69b13a4E276bd81F
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=5000
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
DATA_TRANSPORT_LAYER__CONFIRMATIONS=12
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=localhost
DATA_TRANSPORT_LAYER__SERVER_PORT=7878
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l1
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l1
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=REDACTED_L1_RPC
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=REDACTED_L2_RPC
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
DATA_TRANSPORT_LAYER__L2_CHAIN_ID=10
DATA_TRANSPORT_LAYER__LEGACY_SEQUENCER_COMPATIBILITY=false
```

l2geth's `env.sh`:

```
export CHAIN_ID=10
export DATADIR=/chaindata/optimism/l2geth/gethData
export NETWORK_ID=10
export NO_DISCOVER=true
export NO_USB=true
export GASPRICE=0
export GCMODE=full
export BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F
export BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27
export ETH1_CTC_DEPLOYMENT_HEIGHT=13596466
export ETH1_SYNC_SERVICE_ENABLE=true
export ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A
export ROLLUP_BACKEND=l1
export ROLLUP_CLIENT_HTTP=http://localhost:7878
export ROLLUP_DISABLE_TRANSFERS=false
export ROLLUP_ENABLE_L2_GAS_POLLING=false
export ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159
export ROLLUP_MAX_CALLDATA_SIZE=40000
export ROLLUP_POLL_INTERVAL_FLAG=1s
export ROLLUP_SYNC_SERVICE_ENABLE=true
export ROLLUP_TIMESTAMP_REFRESH=5m
export ROLLUP_VERIFIER_ENABLE=true
export RPC_ADDR=0.0.0.0
export RPC_API=eth,rollup,net,web3,debug
export RPC_CORS_DOMAIN=*
export RPC_ENABLE=true
export RPC_PORT=8545
export RPC_VHOSTS=*
export SEQUENCER_CLIENT_HTTP=REDACTED_L2_RPC
export TARGET_GAS_LIMIT=15000000
export USING_OVM=true
export WS_ADDR=0.0.0.0
export WS_API=eth,rollup,net,web3,debug
export WS_ORIGINS=*
export WS=true
```
