### ISSUE TITLE
Fault Detector 0.4.0 - Not running on bedrock devnet

### ISSUE THREAD

**Issue by andreclaro** [ethereum-optimism/optimism#4652]
**Describe the bug**
Fault detector does not start when including it as part of bedrock devnet: https://github.com/ethereum-optimism/optimism/tree/develop/ops-bedrock

**Steps**
Added fault-detector to bedrock docker-compose and devnet-up.sh.

```
  fault_detector:
    image: ethereumoptimism/fault-detector:0.4.0
    environment:
      FAULT_DETECTOR__L1_RPC_PROVIDER: http://l1:8545
      FAULT_DETECTOR__L2_RPC_PROVIDER: http://l2:8545
    ports:
      - 7350:7300
    depends_on:
      - l1
      - l2
    healthcheck:
      test: [ "CMD-SHELL", "wget -O - http://localhost:7300/api/status" ]
      interval: 10s
      timeout: 120s
      retries: 5

```

**Expected behavior**
Expected to start fault detector.

**Logs**
```
❯  docker logs ops-bedrock-fault_detector-1 -f                                                                                         <aws:dev>

> @eth-optimism/fault-detector@0.4.0 start
> ts-node ./src/service.ts

{"level":30,"time":1673357207696,"msg":"starting app server"}
{"level":30,"time":1673357208258,"port":7300,"hostname":"0.0.0.0","msg":"app server started"}
{"level":30,"time":1673357208260,"msg":"initializing service"}
/opt/optimism/node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:269
        const error: any = new Error(message);
                           ^
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="FRAUD_PROOF_WINDOW()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Interface.decodeFunctionResult (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Contract.<anonymous> (/opt/optimism/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/opt/optimism/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/opt/optimism/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/opt/optimism/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'FRAUD_PROOF_WINDOW()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x0000000000000000000000000000000000000000',
  args: [],
  transaction: {
    data: '0xc17b291b',
    to: '0x0000000000000000000000000000000000000000'
  }
}
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @eth-optimism/fault-detector@0.4.0
npm ERR!   at location: /opt/optimism/packages/fault-detector
npm notice
npm notice New major version of npm available! 8.11.0 -> 9.2.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
npm notice Run `npm install -g npm@9.2.0` to update!
npm notice
```

**System Specs:**
 - OS: MaOS / Docker
 - Package Version (or commit hash): 0.4.0

```
❯ docker --version                                                                                            <aws:dev>
Docker version 20.10.21, build baeda1f
```

```
❯ sw_vers                                                                                                     <aws:dev>
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```
