### ISSUE TITLE
Add dependabot for dependency management. 

### ISSUE THREAD

**Issue by MSevey** [ethereum-optimism/optimism#5764]
**Is your feature request related to a problem? Please describe.**

We are working on an integration with Celestia based on our fork: https://github.com/celestiaorg/optimism

We want to use dependabot to help track changes from upstream repos. 
Since this repo doesn't have dependabot, we enabled it on our repo and immediately received a flood of PRs. 
Ideally our dependabot only watches for updates unique to our repo, and part of this would be ensuring that this repo is also updating its dependancies. 

**Describe the solution you'd like**

Implement dependabot to keep dependencies updated. 

The `yml` file should look like this I believe, happy to open a PR for this
```yml
version: 2
updates:
  - package-ecosystem: docker
    directory: "/ops/docker"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
 ```

**Describe alternatives you've considered**

**Additional context**

**Comment by tynes** [comment]
This is something we could consider after our code freeze is over which will happen after a successful mainnet upgrade

**Comment by ashutosh887** [comment]
I would like to work on this @smartcontracts @MSevey @roninjin10

**Comment by roninjin10** [comment]
@ashutosh887 go for it!  [Here are some docs to get you started ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file).

**Comment by shubhamshd** [comment]
Hi @ashutosh887 just trying to understand your approach, how would you be generating this file?

are you going to use some script to auto-generate or would you be manually generating it?

Because the problem with manually creating the yaml, is that, it will have to be updated every time there is change in the repository. So just trying to understand if somehow we can automate it, we would be be able to put it in GitHub Actions to update Dependabot yaml as required!!!

With my limited knowledge of the project, I would request @smartcontracts @tynes @roninjin10 to suggest the best way possible?

**Comment by MSevey** [comment]
> Hi @ashutosh887 just trying to understand your approach, how would you be generating this file?
> 
> 
> 
> are you going to use some script to auto-generate or would you be manually generating it?
> 
> 
> 
> Because the problem with manually creating the yaml, is that, it will have to be updated every time there is change in the repository. So just trying to understand if somehow we can automate it, we would be be able to put it in GitHub Actions to update Dependabot yaml as required!!!
> 
> 
> 
> With my limited knowledge of the project, I would request @smartcontracts @tynes @roninjin10 @MSevey to suggest the best way possible?

The file I posted in the description of the issue is the file. 

The dependably yml targets package managers for for this project that is go.mod, npm, docker, and GitHub actions. You don't need to update this file very often if ever. The only updates needed would be if a new package manager is added or if you wanted to adjust the dependabot settings for how often and how many PRs are generated for updates.

**Comment by ashutosh887** [comment]
Yes @MSevey I have created some dependabot alerts for some of my personal projects
I would like you to have a look at my PR and help me customize it for other directories as well

Like I can see it only focuses on the ops directory (docker dependencies)
How can we customize it for other directories as well? Like passing other directories in an array or so 🤔

**Comment by MSevey** [comment]
> Yes @MSevey I have created some dependabot alerts for some of my personal projects
> 
> I would like you to have a look at my PR and help me customize it for other directories as well
> 
> 
> 
> Like I can see it only focuses on the ops directory (docker dependencies)
> 
> How can we customize it for other directories as well? Like passing other directories in an array or so 🤔

Unfortunately there isn't. There is a tracking issue for it though 

https://github.com/dependabot/dependabot-core/issues/2178

Best course of action would be for the dev team to manage that at a process level. For example having a policy that all docker files like in the same directory for ease of maintainability.

**Comment by shubhamshd** [comment]
great @ashutosh887 that you kept simple

Nevertheless, I attempted a different approach, and I would highly appreciate it if you could review it once and provide your valuable suggestions. I believe it would be worth my time to consider your input @MSevey @smartcontracts @roninjin10 @tynes 

Here is the link to commit:  https://github.com/shubhamshd/optimism/commit/7d58100a540e677a01e4b286655153e3d70d321f#diff-20a67bde31c712276f176ca9702463fc878b170d5f47e79c12dc1b39f085efb3

**Comment by ashutosh887** [comment]
Oh so you wrote a powershell script to automate this... Cool stuff! @shubhamshd

**Comment by MSevey** [comment]
> great @ashutosh887 that you kept simple
> 
> Nevertheless, I attempted a different approach, and I would highly appreciate it if you could review it once and provide your valuable suggestions. I believe it would be worth my time to consider your input @MSevey @smartcontracts @roninjin10 @tynes
> 
> Here is the link to commit: [shubhamshd@7d58100#diff-20a67bde31c712276f176ca9702463fc878b170d5f47e79c12dc1b39f085efb3](https://github.com/shubhamshd/optimism/commit/7d58100a540e677a01e4b286655153e3d70d321f#diff-20a67bde31c712276f176ca9702463fc878b170d5f47e79c12dc1b39f085efb3)

nice, I think we can do it fully automated in github actions. So on PRs, we try and regenerate and check for a diff. 

give me a few minutes.

**Comment by MSevey** [comment]
This is an edited workflow from a similar feature I did on another project. @shubhamshd you should be able to add this to your branch and target your powershell script. Then anytime someone pushes the workflow will trigger the script and re-generate the dependabot.yml file and commit the updates. 

**NOTE** the default `run` environment in github workflows is `bash` so you'll either need to convert your script or specific the shell environment in the workflow file.

```yml
name: Update Dependabot

on:
  push:

jobs:
  update-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Helper for grabbing the branch name
      - uses: nelonoel/branch-name@v1.0.1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Generate dependabot.yml
        run: /path/to/script >> .github/dependabot.yml

      # Commit the Updates, this only executes if there is a diff
      - name: Commit updates
        uses: test-room-7/action-update-file@v1
        with:
          file-path: .github/dependabot.yml
          commit-msg: Update dependabot.yml from Github Actions
          branch: ${{ env.BRANCH_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
