### ISSUE TITLE
data-transport-layer: TypeError: blocks is not iterable

### ISSUE THREAD

**Issue by miguelmota** [ethereum-optimism/optimism#5837]
**Describe the bug**

Getting the following error when trying to run data-transport-layer docker container for op node replica on goerli.

```sh
{"level":50,"time":1685510560109,"extra":{"message":"TypeError: blocks is not iterable","stack":"TypeError: blocks is not iterable\n    at L2IngestionService._syncSequencerBlocks (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:224:29)\n    at async L2IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:147:17)\n    at async L2IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 2)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}
```

I think the error comes from here:

https://github.com/ethereum-optimism/optimism/blob/affcbad165dd1c698b3d1d098e683ca786402a20/packages/data-transport-layer/src/services/l2-ingestion/service.ts#L327

because `eth_getBlockRange` is a not found method, therefore blocks is undefined.

**To Reproduce**

```yml
version: "3.4"

volumes:
  dtl:
  l2geth:
  scripts:

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3

services:
  data-transport-layer:
    image: ethereumoptimism/data-transport-layer:0.5.49
    container_name: op-dtl
    restart: unless-stopped
    network_mode: host
    environment:
      NETWORK_NAME: goerli
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: https://rpc.ankr.com/eth_goerli
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://goerli.optimism.io
      DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: 0xa6f73589243a6A7a9023b1Fa0651b1d89c177111
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: false
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: true
      DATA_TRANSPORT_LAYER__L1_START_HEIGHT: 7017096
      DATA_TRANSPORT_LAYER__CONFIRMATIONS: 12
      DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS: true
      DATA_TRANSPORT_LAYER__DB_PATH: /db
      DATA_TRANSPORT_LAYER__DEFAULT_BACKEND: l1
      DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND: l1
      DATA_TRANSPORT_LAYER__ENABLE_METRICS: false
      DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME: goerli
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 420
      DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL: 2000
      DATA_TRANSPORT_LAYER__NODE_ENV: production
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 500
      DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE: 0.05
      DATA_TRANSPORT_LAYER__SERVER_HOSTNAME: 0.0.0.0
      DATA_TRANSPORT_LAYER__SERVER_PORT: 7878
      DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL: 1000
    ports:
      - 7878:7878
    volumes:
      - ./optimism_dtl_data:/db
    <<: *logging

  l2geth-replica:
    image: ethereumoptimism/l2geth:0.5.30
    volumes:
      - l2geth:/geth
    container_name: op-replica
    network_mode: host
    depends_on:
      - data-transport-layer
    restart: unless-stopped
    stop_grace_period: 3m
    command:
      - --vmodule=eth/*=5,miner=4,rpc=5,rollup=4,consensus/clique=1
      - --datadir=/geth
      - --allow-insecure-unlock=true
    environment:
      NETWORK_NAME: goerli
      DATADIR: /geth
      CHAIN_ID: 420
      NETWORK_ID: 420
      NO_DISCOVER: true
      NO_USB: true
      GASPRICE: 0
      GCMODE: archive
      BLOCK_SIGNER_ADDRESS: 0x27770a9694e4B4b1E130Ab91Bc327C36855f612E
      BLOCK_SIGNER_PRIVATE_KEY: da5deb73dbc9dea2e3916929daaf079f75232d32a2cf37ff8b1f7140ef3fd9db # from op docs
      BLOCK_SIGNER_PRIVATE_KEY_PASSWORD: pwd
      ETH1_CTC_DEPLOYMENT_HEIGHT: 5619320
      ETH1_L1_FEE_WALLET_ADDRESS: 0xba517B809d22D5e27F607c03dEBDe09d5Ad27049
      ETH1_L1_CROSS_DOMAIN_MESSENGER_ADDRESS: 0x5086d1eEF304eb5284A0f6720f79403b4e9bE294
      ETH1_L1_STANDARD_BRIDGE_ADDRESS: 0x636Af16bf2f682dD3109e60102b8E1A089FedAa8
      ETH1_SYNC_SERVICE_ENABLE: true
      L2GETH_GENESIS_URL: https://storage.googleapis.com/optimism/goerli/goerli-devnet-genesis-2022-06.json
      L2GETH_GENESIS_HASH: 0x1067d2037744f17d34e3ceb88b0d654a3798f5d12b79b348085f13f1ec458636
      L2GETH_BERLIN_ACTIVATION_HEIGHT: 10000
      ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS: 0x4F3F400c20448D33ECc12E7d289F49dA7fC51736
      ROLLUP_BACKEND: l2
      ROLLUP_CLIENT_HTTP: http://data-transport-layer:7878
      ROLLUP_DISABLE_TRANSFERS: false
      ROLLUP_ENABLE_L2_GAS_POLLING: false
      ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS: 0xc8910a1957d276cE5634B978d908B5ef9fB0e05B
      ROLLUP_MAX_CALLDATA_SIZE: 40000
      ROLLUP_POLL_INTERVAL_FLAG: 1s
      ROLLUP_SYNC_SERVICE_ENABLE: true
      ROLLUP_TIMESTAMP_REFRESH: 5m
      ROLLUP_VERIFIER_ENABLE: true
      SEQUENCER_CLIENT_HTTP: https://goerli.optimism.io
      RPC_ADDR: 0.0.0.0
      RPC_API: eth,rollup,net,web3,debug
      RPC_CORS_DOMAIN: "*"
      RPC_ENABLE: true
      RPC_PORT: 8545
      RPC_VHOSTS: "*"
      TARGET_GAS_LIMIT: 15000000
      USING_OVM: true
      WS_ADDR: 0.0.0.0
      WS_API: eth,rollup,net,web3,debug
      WS_ORIGINS: "*"
      WS: true
    ports:
      - 9991:9991
      - 9992:9992
      - 6060:6060
    <<: *logging

  replica-healthcheck:
    image: ethereumoptimism/replica-healthcheck:1.1.13
    container_name: replica-healthcheck
    restart: unless-stopped
    environment:
      NETWORK_NAME: ethereum
      HEALTHCHECK__REFERENCE_RPC_PROVIDER: https://goerli.optimism.io
      HEALTHCHECK__TARGET_RPC_PROVIDER: http://optimism:8545
    <<: *logging
```

**Expected behavior**

**Screenshots**

```sh
docker compose -f docker-compose.yml up
[+] Building 0.0s (0/0)
[+] Running 5/0
 ✔ Container op-dtl                                                                Created                                                                                             0.0s
 ✔ Container replica-healthcheck                                                   Created                                                                                             0.0s
 ! data-transport-layer Published ports are discarded when using host network mode                                                                                                     0.0s
 ✔ Container op-replica                                                            Created                                                                                             0.0s
 ! l2geth-replica Published ports are discarded when using host network mode                                                                                                           0.0s
Attaching to op-dtl, op-replica, replica-healthcheck
op-replica           | running /scripts/check-for-chaindata-berlin.sh
op-replica           | + echo running /scripts/check-for-chaindata-berlin.sh
op-replica           | + GETH_DATA_DIR=/geth
op-replica           | + GETH_CHAINDATA_DIR=/geth/geth/chaindata
op-replica           | + GETH_KEYSTORE_DIR=/geth/keystore
op-replica           | + '[' '!' -d /geth/keystore ]
op-replica           | + '[' '!' -d /geth/geth/chaindata ]
op-replica           | + echo '/geth/geth/chaindata exists, checking for hardfork.'
op-replica           | /geth/geth/chaindata exists, checking for hardfork.
op-replica           | Chain config:
op-replica           | + echo 'Chain config:'
op-replica           | + geth dump-chain-cfg '--datadir=/geth'
op-replica           | INFO [05-31|05:22:38.095] Maximum peer count                       ETH=50 LES=0 total=50
op-replica           | INFO [05-31|05:22:38.095] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
op-replica           | INFO [05-31|05:22:38.095] Allocated cache and file handles         database=/geth/geth/chaindata cache=16.00MiB handles=16
op-replica           | {
op-replica           |   "chainId": 420,
op-replica           |   "homesteadBlock": 0,
op-replica           |   "eip150Block": 0,
op-replica           |   "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
op-replica           |   "eip155Block": 0,
op-replica           |   "eip158Block": 0,
op-replica           |   "byzantiumBlock": 0,
op-replica           |   "constantinopleBlock": 0,
op-replica           |   "petersburgBlock": 0,
op-replica           |   "istanbulBlock": 0,
op-replica           |   "muirGlacierBlock": 0,
op-replica           |   "berlinBlock": 0,
op-replica           |   "clique": {
op-replica           |     "period": 0,
op-replica           |     "epoch": 30000
op-replica           |   }
op-replica           | }
op-replica           | + geth dump-chain-cfg '--datadir=/geth'
op-replica           | + grep -q '"berlinBlock": 10000'
op-replica           | INFO [05-31|05:22:38.136] Maximum peer count                       ETH=50 LES=0 total=50
op-replica           | INFO [05-31|05:22:38.136] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
op-replica           | INFO [05-31|05:22:38.136] Allocated cache and file handles         database=/geth/geth/chaindata cache=16.00MiB handles=16
op-replica           | Hardfork not activated, running init.
op-replica           | + echo 'Hardfork not activated, running init.'
op-replica           | + geth init '--datadir=/geth' https://storage.googleapis.com/optimism/goerli/goerli-devnet-genesis-2022-06.json 0x1067d2037744f17d34e3ceb88b0d654a3798f5d12b79b348085f13f1ec458636
op-replica           | INFO [05-31|05:22:38.172] Fetching genesis file                    url=https://storage.googleapis.com/optimism/goerli/goerli-devnet-genesis-2022-06.json
op-replica           | INFO [05-31|05:22:38.295] Maximum peer count                       ETH=50 LES=0 total=50
op-replica           | INFO [05-31|05:22:38.295] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
op-replica           | INFO [05-31|05:22:38.296] Allocated cache and file handles         database=/geth/geth/chaindata cache=16.00MiB handles=16
op-replica           | INFO [05-31|05:22:38.311] Persisted trie from memory database      nodes=45 size=30.65KiB time=145.33µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-1024.00B
op-replica           | INFO [05-31|05:22:38.312] Successfully wrote genesis state         database=chaindata            hash=c1fc15…354be1
op-replica           | INFO [05-31|05:22:38.312] Allocated cache and file handles         database=/geth/geth/lightchaindata cache=16.00MiB handles=16
op-replica           | INFO [05-31|05:22:38.319] Persisted trie from memory database      nodes=45 size=30.65KiB time=77.485µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-1024.00B
op-replica           | INFO [05-31|05:22:38.319] Successfully wrote genesis state         database=lightchaindata            hash=c1fc15…354be1
op-replica           | + echo 'geth hardfork activation complete'
op-replica           | geth hardfork activation complete
op-replica           | errexit         on
op-replica           | noglob          off
op-replica           | ignoreeof       off
op-replica           | monitor         off
op-replica           | noexec          off
op-replica           | xtrace          off
op-replica           | verbose         off
op-replica           | noclobber       off
op-replica           | allexport       off
op-replica           | notify          off
op-replica           | nounset         off
op-replica           | vi              off
op-replica           | pipefail        off
op-replica           | INFO [05-31|05:22:38.361] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
op-replica           | INFO [05-31|05:22:38.361] Enabling metrics collection
op-replica           | INFO [05-31|05:22:38.362] Maximum peer count                       ETH=50 LES=0 total=50
op-replica           | INFO [05-31|05:22:38.362] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
op-replica           | INFO [05-31|05:22:38.363] Starting peer-to-peer node               instance=Geth/v1.9.10-stable/linux-amd64/go1.18
op-replica           | INFO [05-31|05:22:38.363] Allocated trie memory caches             clean=512.00MiB dirty=0.00B
op-replica           | INFO [05-31|05:22:38.363] Allocated cache and file handles         database=/geth/geth/chaindata cache=512.00MiB handles=536870908
op-replica           | INFO [05-31|05:22:38.377] Opened ancient database                  database=/geth/geth/chaindata/ancient
op-replica           | INFO [05-31|05:22:38.378] Initialised chain configuration          config="{ChainID: 420 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: 0, Engine: clique}"
op-replica           | INFO [05-31|05:22:38.378] Initialising Ethereum protocol           versions="[64 63]" network=420 dbversion=7
op-replica           | INFO [05-31|05:22:38.378] Loaded most recent local header          number=0 hash=c1fc15…354be1 td=1 age=54y2mo1w
op-replica           | INFO [05-31|05:22:38.378] Loaded most recent local full block      number=0 hash=c1fc15…354be1 td=1 age=54y2mo1w
op-replica           | INFO [05-31|05:22:38.378] Loaded most recent local fast block      number=0 hash=c1fc15…354be1 td=1 age=54y2mo1w
op-replica           | INFO [05-31|05:22:38.378] Loaded local transaction journal         transactions=0 dropped=0
op-replica           | INFO [05-31|05:22:38.378] Regenerated local transaction journal    transactions=0 accounts=0
op-replica           | INFO [05-31|05:22:38.378] Running in verifier mode                 sync-backend=l2
op-replica           | INFO [05-31|05:22:38.378] Configured rollup client                 url=http://data-transport-layer:7878 chain-id=420 ctc-deploy-height=5619320
op-replica           | INFO [05-31|05:22:38.392] Cannot connect to upstream service       msg="Cannot connect to data service: Cannot fetch eth context: Get \"http://data-transport-layer:7878/eth/context/latest\": dial tcp: lookup data-transport-layer on 192.168.10.1:53: no such host"
replica-healthcheck  |
replica-healthcheck  | > @eth-optimism/replica-healthcheck@1.1.13 start
replica-healthcheck  | > ts-node ./src/service
replica-healthcheck  |
op-dtl               | {"level":30,"time":1685510559046,"msg":"Service is starting..."}
op-dtl               | {"level":30,"time":1685510559047,"msg":"Service is initializing..."}
op-dtl               | {"level":30,"time":1685510559047,"msg":"Initializing L1 Data Transport Service..."}
op-dtl               | {"level":30,"time":1685510559062,"msg":"L2 chain ID is: 420"}
op-dtl               | {"level":30,"time":1685510559062,"msg":"BSS HF1 will activate at: 0"}
op-dtl               | {"level":30,"time":1685510559068,"msg":"Service is initializing..."}
op-dtl               | {"level":30,"time":1685510559075,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
op-dtl               | {"level":30,"time":1685510559075,"url":"http://44.200.12.199:8545","msg":"HTTP Server L1 RPC Provider initialized"}
op-dtl               | {"level":30,"time":1685510559075,"url":"https://goerli.optimism.io","msg":"HTTP Server L2 RPC Provider initialized"}
op-dtl               | {"level":30,"time":1685510559076,"msg":"Service has initialized."}
op-dtl               | {"level":30,"time":1685510559076,"msg":"Service is initializing..."}
op-dtl               | {"level":30,"time":1685510559076,"msg":"Service has initialized."}
op-dtl               | {"level":30,"time":1685510559076,"msg":"Service has initialized."}
op-dtl               | {"level":30,"time":1685510559077,"msg":"Service is starting..."}
op-dtl               | {"level":30,"time":1685510559077,"msg":"Service is starting..."}
op-dtl               | {"level":30,"time":1685510559080,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
op-dtl               | {"level":30,"time":1685510559081,"msg":"Service has started"}
op-dtl               | {"level":30,"time":1685510559753,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
op-dtl               | {"level":50,"time":1685510560109,"extra":{"message":"TypeError: blocks is not iterable","stack":"TypeError: blocks is not iterable\n    at L2IngestionService._syncSequencerBlocks (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:224:29)\n    at async L2IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:147:17)\n    at async L2IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 2)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhan
```

![DeepinScreenshot_select-area_20230530222436](https://github.com/ethereum-optimism/optimism/assets/168240/a0220704-881a-482a-8c6c-78cb9ab9ce56)

**System Specs:**
 - OS: Docker
 - Package Version (or commit hash):

**Additional context**
