### ISSUE TITLE
op-node connect to op-geth with followed error

### ISSUE THREAD

**Issue by lcgogo** [ethereum-optimism/optimism#5908]
op-node connect to op-geth with followed error
```
t=2023-06-07T14:42:48+0000 lvl=info msg="loaded new runtime config values!" p2p_seq_address=0xAAAA45d9549EDA09E70937013520214382Ffc4A2
t=2023-06-07T14:42:48+0000 lvl=eror msg="Error initializing the rollup node" err="403 Forbidden: invalid host specified\n"
t=2023-06-07T14:42:48+0000 lvl=eror msg="Unable to create the rollup node"   error="403 Forbidden: invalid host specified\n"
t=2023-06-07T14:42:48+0000 lvl=crit msg="Application failed"                 message="403 Forbidden: invalid host specified\n"
```

I use a docker-compose to run op-geth + op-node
```
version: '3'

services:
  "op-geth":
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:db683328028fc16403fc555844556a42a337a148
    container_name: opt2_1.0_1
    user: "nobody:nogroup"
    ports:
      - ${RPCPORT:-8545}:8545
      - ${WS_PORT:-8546}:8546
      - ${AUTH_PORT:-8551}:8551
    volumes:
      - /data/opt2:/data/opt2
    environment:
      - COIN_NAME=opt2
    entrypoint:
      - /usr/local/bin/geth
      - --ws
      - --ws.port=8546
      - --ws.addr=0.0.0.0
      - --ws.origins="*"
      - --http
      - --http.addr=0.0.0.0
      - --http.api="eth,net,web3,debug"
      - --http.port=8545
      - --http.vhosts="*"
      - --http.corsdomain="*"
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/data/opt2/jwt.txt
      - --authrpc.port=8551
      - --authrpc.vhosts="*"
      - --datadir=/data/opt2
      - --verbosity=3
      - --rollup.disabletxpoolgossip=true
      - --rollup.sequencerhttp=https://bedrock-beta-1-sequencer.optimism.io
      - --nodiscover
      - --syncmode=full
      - --maxpeers=0
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "10"
  "op-node":
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:d826cb018955d342779ccc0ebdf878cfa746e765
    container_name: opt-node_1.1.0
    volumes:
      - /data/opt2:/data/opt2
    ports:
      - "${OP_NODE_RPC_PORT:-9545}:9545"
    entrypoint:
      - /usr/local/bin/op-node
      - --l1=http://geth:8545
      - --l2=http://op-geth:8551
      - --network=mainnet
      - --rpc.addr=0.0.0.0
      - --rpc.port=9545
      - --l2.jwt-secret=/data/opt2/jwt.txt
      - --log.level=debug
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "10"
    depends_on:
      - op-geth
```

I try connet http://op-geth:8551 is ok in another container
```
/ # ls /data/opt2/jwt.txt
/data/opt2/jwt.txt
/ # cat /data/opt2/jwt.txt
c751f6cb3e5c0507b65b850956dc3581f02fe498c33afa3d332cd10f5fbad639
/ # curl op-geth:8551
missing token
```
