### ISSUE TITLE
[Feature] Keep Horizontal scaling using docker-compose

### ISSUE THREAD

**Issue by netzulo** [ethereum-optimism/optimism#6410]
### Behaviour obtained

Can't start with new bedrock ops multiples nodes connected with custom L1+L2 using "deploy" key from docker compose

### Behaviour expected

Can start with new bedrock ops multiples nodes connected with custom L1+L2 using "deploy" key from docker compose

#### Notes
Before bedrock update exists "replica" as a different container to allow create multiples nodes connecting to your own L2+L1.
Now the docker configuration just include configuration for l1,l2,"deployer" as python script, batcher, proposer op-node and stateviz

maybe im missunderstanding something, if i want to generate my 10 deploy(docker funtionality) of "replica" old container with new bedrock update, why we are not maintaining this kind of "docker-compose files" ?

i mean, instead of using just this guide https://stack.optimism.io/docs/build/getting-started/#initialize-op-geth
we can have something like 

```
# /ops-bedrock/docker-compose.l2-nodes.yml
services:
op-node:
  deploy:
      replicas: 10
  # all node config
op-geth:
  deploy:
      replicas: 10
  # all geth config
```

:pray: as QA , i think we will want to create strange scenarios to improve productivity.

**Comment by tynes** [comment]
Do you want to add additional "replica" nodes to the docker compose setup? ie full nodes that are just syncing the network? What is your usecase?

**Comment by netzulo** [comment]
i think im not totally sure what i really need, but, before bedrock, i had this services working with hardhat as L1

```
l1
deployer
dtl
l2
relayer
fault-detector
submitter
gasoracle
verifier
replica
replica-healthcheck
# and all influxdb services
```
and now just i need to understand

```
l1
l2
op-batcher
op-proposer
op-node
stateviz
```
+ make+python+nodejs, i really love you xD

Now we have a realistict L1+L2+NODE(op-node+op-geth) datadirs and block production, but i think we can make more flexible all docker based configurations

I will list 2 "maybe" interesting fixes for this 

1.  still exists `Dockerfile.packages` with different services so is possible to maintain last known configurations as separated docker file, people like "blockscout explorer" have a directory with differents users ready `docker-compose.something.yml` files, so with python and make, all is easy to implement and document at this point

2. I can understand what a L2-node is a sum of op-node+op-geth connected between datadir and genesis from L2 ( maybe im saying something wrong) so, if this is true we can have a separated file named `docker-compose.l2-nodes.yml`, configured with cappabilities to use "deploy" tag from docker compose to generate all what user want it

![image](https://github.com/ethereum-optimism/optimism/assets/11871932/cc29758f-c724-4f02-9fda-111c4c737583)
i based point 2 of this image from this ref https://community.optimism.io/docs/developers/bedrock/node-operator-guide/#deployment-overview

### Scenarios

+ Concurrency, ye.. is distributed, but still dapps connect to different endpoints (RPC urls) so can be interesting
+ Ready docker compose configuration for DAPP (not a web, not a contract, just a little config with many comments "not source compiler users"
+ Custom blockchain update % of total nodes with new GETH versions and/or L1/L2 upgrades


### Just a note

I did this in local and is working but not at 100% , im testing some things.

 **be carefull if some reader want to copy this in the future**
```
version: '3.9'
name: optimism

# Networks to be used by services
networks:
  op-network:
    name: op-network
    driver: bridge

# This Compose file is expected to be used with the devnet-up.sh script.
# The volumes below mount the configs generated by the script into each
# service.

volumes:
  l1_data:
  l2_data:
  op_log:
  geth_data:


services:
  l1:
    container_name: l1
    build:
      context: .
      dockerfile: Dockerfile.l1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "9551:8551"
      - "7060:6060"
    volumes:
      - "l1_data:/db"
      - "${PWD}/../.devnet/genesis-l1.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"

  l2:
    container_name: l2
    build:
      context: .
      dockerfile: Dockerfile.l2
    ports:
      - "9545:8545"
      - "9552:8551"
      - "8060:6060"
    volumes:
      - "l2_data:/db"
      - "${PWD}/../.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
    entrypoint:  # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"

  op-node:
    container_name: op-node
    depends_on:
      - l1
      - l2
    build:
      context: ../
      dockerfile: ./op-node/Dockerfile
    command: >
      op-node
      --l1=ws://l1:8546
      --l2=http://l2:8551
      --l2.jwt-secret=/config/test-jwt-secret.txt
      --sequencer.enabled
      --sequencer.l1-confs=0
      --verifier.l1-confs=0
      --p2p.sequencer.key=8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8545
      --p2p.listen.ip=0.0.0.0
      --p2p.listen.tcp=9003
      --p2p.listen.udp=9003
      --p2p.scoring.peers=light
      --p2p.ban.peers=true
      --snapshotlog.file=/op_log/snapshot.log
      --p2p.priv.path=/config/p2p-node-key.txt
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --pprof.enabled
      --rpc.enable-admin
    ports:
      - "7545:8545"
      - "9003:9003"
      - "7300:7300"
      - "6060:6060"
    volumes:
      - "${PWD}/p2p-sequencer-key.txt:/config/p2p-sequencer-key.txt"
      - "${PWD}/p2p-node-key.txt:/config/p2p-node-key.txt"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
      - "${PWD}/../.devnet/rollup.json:/rollup.json"
      - op_log:/op_log

  op-proposer:
    container_name: op-proposer
    depends_on:
      - l1
      - l2
      - op-node
    build:
      context: ../
      dockerfile: ./op-proposer/Dockerfile
    ports:
      - "6062:6060"
      - "7302:7300"
    environment:
      OP_PROPOSER_L1_ETH_RPC: http://op-l1:8545
      OP_PROPOSER_ROLLUP_RPC: http://op-node:8545
      OP_PROPOSER_POLL_INTERVAL: 1s
      OP_PROPOSER_NUM_CONFIRMATIONS: 1
      OP_PROPOSER_MNEMONIC: test test test test test test test test test test test junk
      OP_PROPOSER_L2_OUTPUT_HD_PATH: "m/44'/60'/0'/0/1"
      OP_PROPOSER_L2OO_ADDRESS: "${L2OO_ADDRESS}"
      OP_PROPOSER_PPROF_ENABLED: "true"
      OP_PROPOSER_METRICS_ENABLED: "true"
      OP_PROPOSER_ALLOW_NON_FINALIZED: "true"

  op-batcher:
    container_name: op-batcher
    depends_on:
      - l1
      - l2
      - node
    build:
      context: ../
      dockerfile: ./op-batcher/Dockerfile
    ports:
      - "6061:6060"
      - "7301:7300"
      - "6545:8545"
    environment:
      OP_BATCHER_L1_ETH_RPC: http://l1:8545
      OP_BATCHER_L2_ETH_RPC: http://l2:8545
      OP_BATCHER_ROLLUP_RPC: http://op-node:8545
      OP_BATCHER_MAX_CHANNEL_DURATION: 1
      OP_BATCHER_SUB_SAFETY_MARGIN: 4 # SWS is 15, ChannelTimeout is 40
      OP_BATCHER_POLL_INTERVAL: 1s
      OP_BATCHER_NUM_CONFIRMATIONS: 1
      OP_BATCHER_MNEMONIC: test test test test test test test test test test test junk
      OP_BATCHER_SEQUENCER_HD_PATH: "m/44'/60'/0'/0/2"
      OP_BATCHER_PPROF_ENABLED: "true"
      OP_BATCHER_METRICS_ENABLED: "true"
      OP_BATCHER_RPC_ENABLE_ADMIN: "true"

  stateviz:
    build:
      context: ../
      dockerfile: ./ops-bedrock/Dockerfile.stateviz
    command:
      - stateviz
      - -addr=0.0.0.0:8080
      - -snapshot=/op_log/snapshot.log
      - -refresh=10s
    ports:
      - "9090:8080"
    volumes:
      - op_log:/op_log:ro

  create-geth-genesis:
    container_name: create-geth-genesis
    depends_on:
      - l1
      - l2
      - op-node
    build:
      context: ./../op-geth
      dockerfile: ./Dockerfile
    volumes:
      - "geth_data:/home/datadir/"
      - "${PWD}/../.devnet/genesis-l2.json:/config/genesis.json"
    command: init --datadir /home/datadir /config/genesis.json

  op-geth:
    container_name: op-geth
    depends_on:
      create-geth-genesis:
        condition: service_completed_successfully
    build:
      context: ./../op-geth
      dockerfile: ./Dockerfile
    ports:
      - "8549:8545"
      - "8550:8546"
    volumes:
      - "geth_data:/home/datadir/"
      - "${PWD}/test-jwt-secret.txt:/config/jwt.txt"
      - "${PWD}/../.devnet/genesis-l2.json:/config/genesis.json"
    environment:
      L1_RPC: http://l1:8545
      L2_RPC: http://l2:8545
      SEQUENCER_URL: http://op-node:8545
    command: >
      --http
      --http.corsdomain="*"
      --http.vhosts="*"
      --http.addr=0.0.0.0
      --http.api=web3,debug,eth,txpool,net,engine,miner
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins="*"
      --ws.api=web3,debug,eth,txpool,net,engine,miner
      --syncmode=full
      --gcmode=archive
      --nodiscover
      --maxpeers=0
      --networkid=901
      --authrpc.vhosts="*"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.jwtsecret=/config/jwt.txt
      --rollup.sequencerhttp=http://op-node:8545
      --datadir /home/datadir
#     --snapshot=false
#     --rollup.disabletxpoolgossip=true

```

let me know if i'm misunderstanding something please @tynes
