### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid because: Unsupported config option for services.builder: 'scale'

### ISSUE THREAD

**Issue by kesar** [ethereum-optimism/optimism#690]
https://github.com/docker/compose/issues/7722#issuecomment-686466786

getting some error running docker compose https://github.com/ethereum-optimism/optimism/blob/master/ops/docker-compose.yml#L9

i think v3 does not support scale
that was added 20h ago ( https://github.com/ethereum-optimism/optimism/commit/f388b7aade9bb398a9033642ad16ea5a59a71e96  )

➜  ops git:(master) docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because: Unsupported config option for services.builder: 'scale'

**Comment by snario** [comment]
What version of `docker-compose` is running on Github Actions?

**Comment by tynes** [comment]
This works on my machine and in github actions

Which version of docker/docker-compose are you useing @kesar?

**Comment by kesar** [comment]
> Which version of docker/docker-compose are you useing @kesar?

I will report version in few hours once I am back in the office 👍🏻

**Comment by kesar** [comment]
➜  ~ docker -v
Docker version 20.10.3, build 48d30b5
➜  ~ docker-compose -v
docker-compose version 1.21.2, build a133471

**Comment by gakonst** [comment]
Could you try upgrading docker-compose?

```
Docker version 20.10.5, build 55c4c88
docker-compose version 1.28.5, build c4eb3a1f
```

**Comment by kesar** [comment]
sure, i will try with new version 👍, but anyhow scale is deprecated in v3 so most likely the solution could be using replicas like:
``` 
version: "3"

services:
  # base service builder
  builder:
    image: ethereumoptimism/builder
    deploy:
       replicas: 0
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.monorepo
      ....
      
```
