### ISSUE TITLE
Unable to deploy op-node 

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#7179]
I am deploying my OP-Stack chain on the Kubernetes cluster. I am using helm charts and op-geth, op-node docker Images. my op-geth is running successfully in a pod.

but when I am trying to run the op-node I am getting RPC error. I am using op-node Docker Image from release-[1.1.4](https://us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.1.4) . 

**my values.yaml file -** 

```
replicaCount: 1

image:
  repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: d826cb018955d342779ccc0ebdf878cfa746e765

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#######################################
# op-node settings for Goerli testnet.
#######################################
livenessProbe: true
readinessProbe: true

secretForVolumeMountDir: /secrets
configmapsForVolumeMountDir: /configmaps

l1:
  rpcAddr: https://eth-goerli.g.alchemy.com/v2/e0CsbXjGCT0xVVFc9MyaE7-olvSVAh4S
  rpcKind: alchemy

l2:
  rpcAddr: http://0.0.0.0:8551
  jwtSecret:
    file: abf3a433bfe1f8faa262ad82b3ec5fa572e9c045a4c44bd3b21998e77fd3632a
    filename: jwt-secret.txt

sequencer:
  enabled: true
 # l1Confirmations: 3
  p2pKey: 87ab7e053da865130601efdb8fdd22d0197bab98fb7435fadac73cab6ed94fcc

#verifier:
#  l1Confirmations: 3

p2p:
  enabled: true
  priv:
    file:
    filename: p2ppriv.txt
  listen:
    ip: 0.0.0.0
    tcp:
      name: p2p-tcp-port
      containerPort: 9003
      hostPort: 9003
    udp:
      name: p2p-udp-port
      containerPort: 9003
      hostPort: 9003

rollupConfig:
  filename: rollup.json

rpc:
  port:
    name: rpc-port
    containerPort: 8547
    hostPort: 8547
  addr: 0.0.0.0
  enableAdmin: true

metrics:
  enabled: true
  addr: 0.0.0.0
  port:
    name: metrics-port
    containerPort: 7300
    hostPort: 7300

# rest application arguments
args: []

```
**Error -**

![image](https://github.com/ethereum-optimism/optimism/assets/96972634/25232562-e849-4f65-abbd-4029ea1daa0f)

I checked my Alchemy RPC, it has no issues with my L1 Goerli RPC.

**helm chart that I'm using -**
https://artifacthub.io/packages/helm/op-chain-charts/op-node
